(()=>{
'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(n/1000)*1000)+' ₽';
const progress=$('#progress'),sticky=$('#sticky');let scrollRaf=0;
function onScroll(){if(scrollRaf)return;scrollRaf=requestAnimationFrame(()=>{scrollRaf=0;const h=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(h>0?scrollY/h*100:0)+'%';sticky?.classList.toggle('show',scrollY>520);});}
addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});onScroll();
const ba=$('#beforeAfter'),afterLayer=$('#afterLayer'),divider=$('#baDivider'),handle=$('#baHandle');let baPos=52,dragging=false,userTouched=false,startX=0,startY=0,horizontal=false;
function setBA(pos,animate=true){if(!ba)return;baPos=Math.max(0,Math.min(100,pos));ba.style.setProperty('--pos',baPos+'%');ba.style.setProperty('--ba-full',ba.getBoundingClientRect().width+'px');if(afterLayer)afterLayer.style.width=baPos+'%';if(divider)divider.style.left=baPos+'%';if(handle)handle.setAttribute('aria-valuenow',String(Math.round(baPos)));if(!animate){afterLayer?.style.setProperty('transition','none');divider?.style.setProperty('transition','none');requestAnimationFrame(()=>{afterLayer?.style.removeProperty('transition');divider?.style.removeProperty('transition');});}$$('.compare-toggle button').forEach(b=>b.classList.toggle('active',(b.dataset.ba==='before'&&baPos<8)||(b.dataset.ba==='after'&&baPos>92)||(b.dataset.ba==='split'&&baPos>=8&&baPos<=92)));}
function setBAFromClientX(x){if(!ba)return;const r=ba.getBoundingClientRect();setBA((x-r.left)/r.width*100,false);}
if(ba){setBA(52,false);addEventListener('resize',()=>setBA(baPos,false),{passive:true});ba.addEventListener('pointerdown',e=>{userTouched=true;dragging=true;horizontal=false;startX=e.clientX;startY=e.clientY;ba.setPointerCapture?.(e.pointerId);});ba.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(!horizontal&&Math.abs(dx)>8&&Math.abs(dx)>Math.abs(dy))horizontal=true;if(horizontal){e.preventDefault();setBAFromClientX(e.clientX);}});const end=e=>{dragging=false;horizontal=false;ba.releasePointerCapture?.(e.pointerId)};ba.addEventListener('pointerup',end);ba.addEventListener('pointercancel',end);handle?.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){userTouched=true;setBA(baPos-5);e.preventDefault()}if(e.key==='ArrowRight'){userTouched=true;setBA(baPos+5);e.preventDefault()}if(e.key==='Home'){userTouched=true;setBA(0);e.preventDefault()}if(e.key==='End'){userTouched=true;setBA(100);e.preventDefault()}});$$('.compare-toggle button').forEach(b=>b.addEventListener('click',()=>{userTouched=true;setBA(b.dataset.ba==='before'?0:b.dataset.ba==='after'?100:52);}));if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){io.disconnect();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;setTimeout(()=>{if(!userTouched)setBA(14)},250);setTimeout(()=>{if(!userTouched)setBA(86)},1150);setTimeout(()=>{if(!userTouched)setBA(52)},2600);}},{threshold:.42});io.observe(ba);}}
const lossArticles=$$('#lossStory article'),lossTotal=$('#lossTotal');let lossSum=0;
if('IntersectionObserver'in window&&lossArticles.length){const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(!e.isIntersecting||e.target.dataset.done)return;e.target.dataset.done='1';e.target.classList.add('active');lossSum+=Number(e.target.dataset.add||0);animateNumber(lossTotal,lossSum,520);});},{threshold:.58});lossArticles.forEach(a=>io.observe(a));}else{lossArticles.forEach(a=>a.classList.add('active'));lossSum=lossArticles.reduce((s,a)=>s+Number(a.dataset.add||0),0);if(lossTotal)lossTotal.textContent=money(lossSum);}
function animateNumber(el,to,duration=650){if(!el)return;const from=Number(el.dataset.current||String(el.textContent).replace(/\D/g,'')||0),start=performance.now();cancelAnimationFrame(el._raf);function tick(now){const t=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-t,3),v=Math.round(from+(to-from)*eased);el.textContent=money(v);if(t<1)el._raf=requestAnimationFrame(tick);else el.dataset.current=String(to);}el._raf=requestAnimationFrame(tick);}
const modes={replace:{label:'Сценарий A · Полная замена',title:'Разбираем готовую конструкцию и собираем процесс заново',money:312000,days:'18–21 день',result:'Риск переноса сроков',resultText:'Пять этапов и несколько исполнителей',active:['measure','production','delivery','dismantle','finish']},restore:{label:'Сценарий B · Восстановление',title:'Работаем с установленным стеклом непосредственно на объекте',money:96000,days:'около 2 дней',result:'Потенциальная экономия — 216 000 ₽',resultText:'Без производства, логистики и демонтажа',active:['measure','finish']}};
const scenarioLabel=$('#scenarioLabel'),scenarioTitle=$('#scenarioTitle'),modeMoney=$('#modeMoney'),modeDays=$('#modeDays'),modeResult=$('#modeResult'),modeResultText=$('#modeResultText'),timelineItems=$$('#timeline>div');let scenarioTouched=false;
function setMode(name,user=false){const m=modes[name];if(!m)return;if(user)scenarioTouched=true;$$('.scenario-switch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===name));if(scenarioLabel)scenarioLabel.textContent=m.label;if(scenarioTitle)scenarioTitle.textContent=m.title;animateNumber(modeMoney,m.money,650);if(modeDays)modeDays.textContent=m.days;if(modeResult)modeResult.textContent=m.result;if(modeResultText)modeResultText.textContent=m.resultText;timelineItems.forEach(el=>el.classList.toggle('off',!m.active.includes(el.dataset.step)));}
$$('.scenario-switch button').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode,true)));setMode('replace');const scenario=$('#scenario');if(scenario&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){io.disconnect();setTimeout(()=>{if(!scenarioTouched)setMode('restore')},1100)}},{threshold:.38});io.observe(scenario);}
const form=$('#qualForm'),qualTitle=$('#qualTitle'),qualSaving=$('#qualSaving');
function qualify(){if(!form)return null;const d=new FormData(form),area=Math.max(.2,Number(d.get('area'))||.2),replacement=Number(d.get('replacement'))||0,object=d.get('object'),damage=d.get('damage');let low=27,high=49;if(area>10){low+=7;high+=9}if(replacement>150000){low+=8;high+=9}if(object==='construction'||object==='commercial'){low+=4;high+=5}if(damage==='construction'||damage==='haze'){low+=3;high+=4}if(damage==='welding'){low-=5;high-=3}low=Math.max(18,Math.min(55,low));high=Math.max(low+8,Math.min(67,high));if(qualSaving)qualSaving.textContent=low+'–'+high+'%';if(qualTitle)qualTitle.textContent=high>=60?'Высокий потенциал экономии — отправьте фото':'Восстановление имеет смысл рассмотреть';return{d,low,high,replacement};}
form?.addEventListener('input',qualify);qualify();$('#sendQual')?.addEventListener('click',()=>{const r=qualify(),d=r.d,object=form.object.options[form.object.selectedIndex].text,damage=form.damage.options[form.damage.selectedIndex].text,text=`Здравствуйте. Хочу проверить возможность восстановления стекла.\nОбъект: ${object}\nПлощадь: ${d.get('area')} м²\nПовреждение: ${damage}\nИзвестная стоимость замены: ${r.replacement?money(r.replacement):'не указана'}\nГотов отправить фотографии.`;window.open('https://t.me/zhukov_boss?text='+encodeURIComponent(text),'_blank','noopener');});
$$('[data-track]').forEach(el=>el.addEventListener('click',()=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:el.dataset.track});}));
})();